# fly.toml app configuration file generated for 2025-ssafy-drugai-backend-little-surf-2988 on 2025-07-03T11:30:52+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '2025-ssafy-drugai-backend-little-surf-2988'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
